- TestApps/TestAppSwiftUI/ContentView.swift
Update the test data sent in the track state and track action calls to match the examples in the data prep tutorial.
> Update test app sample data to match tutorial

- AEPEdgeBridge.podspec
- AEPEdgeBridge.xcodeproj/project.pbxproj
- Podfile.lock
- README.md
- Sources/EdgeBridgeConstants.swift
- Tests/FunctionalTests/EdgeBridgeFunctionalTests.swift
Update version to 1.0.0 and remove beta flag.
Update README to remove Beta warning.
Update Pods to latest, which updates Edge to 1.5.0.
> Update version to 1.0.0

- Documentation/tutorials/EdgeBridgeTutorialAppFinal/EdgeBridgeTutorialApp.xcodeproj/project.pbxproj
- Documentation/tutorials/EdgeBridgeTutorialAppFinal/EdgeBridgeTutorialApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Documentation/tutorials/edge-bridge-tutorial.md
This PR updates the Edge Bridge tutorial document and Final app references to `dev` resources to point to `main` instead, now that Edge Bridge iOS is officially released.
This PR is based on the `main` branch, and should not have the downmerge commits from the `dev` branch.
> Update tutorial references from `dev` to `main`

- Documentation/tutorials/EdgeBridgeTutorialAppFinal/EdgeBridgeTutorialApp.xcodeproj/project.pbxproj
- Documentation/tutorials/EdgeBridgeTutorialAppFinal/EdgeBridgeTutorialApp.xcodeproj/project.xcworkspace/xcshareddata/swiftpm/Package.resolved
- Documentation/tutorials/edge-bridge-tutorial.md
> Down merge main to dev: Update dev resources to main (#33)

- Makefile
Update ci-pod-repo-update in makefile
> Update ci-pod-repo-update in makefile

- Makefile
Update ci-pod-repo-update in makefile
> Update ci-pod-repo-update in makefile (#43)

- Makefile
> update archive zip file name

- .github/workflows/update_versions.yml
- AEPEdgeBridge.podspec
- AEPEdgeBridge.xcodeproj/project.pbxproj
- Makefile
- Script/update-versions.sh
- Sources/EdgeBridgeConstants.swift
- Updates version to v4.1.0 in preparation for the release, including the event chaining feature
- Adds tooling for updating the version on demand with workflow runs (similar to the Edge extension)
> Updates version to v4.1.0 and adds tooling for updating version on workflow run

- Podfile.lock
> Update pods to pull Edge 4.1.0

- .circleci/config.yml
- .github/workflows/release.yml
- AEPEdgeBridge.podspec
- AEPEdgeBridge.xcodeproj/project.pbxproj
- Documentation/getting-started.md
- Makefile
- Package.swift
- Podfile
- Podfile.lock
- README.md
- Script/test-SPM.sh
- Script/test-podspec.sh
- Sources/EdgeBridgeConstants.swift
- Updates minimum supported iOS, tvOS to 12.0
- Fixes podspec verification failure
- CircleCI, workflow Xcode updates
- Readme updates
> EdgeBridge v5.0.0

- Documentation/README.md
- Documentation/api-reference.md
- Documentation/data-format.md
Adds documentation outlining how the tracking data is mapped to the Experience Event's "data" element.
> Add documentation outlining the new data format in v5

- Podfile
- Podfile.lock
> Merge main changes + staging pods

- Podfile
- Podfile.lock
This PR fixes the `AEPTestUtils` tag from `v5.0.0` to the conventional `5.0.0`
> Fix AEPTestUtils tag

- Sources/EdgeBridge.swift
- Tests/FunctionalTests/EdgeBridgeFunctionalTests.swift
This PR fixes warnings for deprecated test helper APIs - updated to use latest APIs
> Fix warnings

- Podfile
- Podfile.lock
> pod update

- Podfile
- Podfile.lock
> podfile update

- Documentation/data-format.md
Update the data-format.md documentation with some minor fixes and word changes which were applied to the same documentation in the Android repo. Add a link to the full list of data variable mappings in Experience League.
> Update format and wording of data-format documentation

- Documentation/data-format.md
Down merge from Main to Dev to update `data-format` documentation.
> Down merge Main to Dev to update docs

- Documentation/data-format.md
Specify "linkType" is set to "other".
> [doc] Update data-format.md linkType to "other"

- Documentation/tutorials/edge-bridge-tutorial.md
* Update edge-bridge-tutorial.md
* review changes
> sync dev-main with latest doc changes
